
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eztvmldryyubxorcdbtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6dHZtbGRyeXl1YnhvcmNkYnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjkyNDMsImV4cCI6MjA2MTEwNTI0M30.2xL2JUd71ddnXbLkZgQmgh1ahsbxZW02PuiYVNrOhjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
  },
});
